version: "3.8"
services:
  database:
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=mina
      - POSTGRES_PASSWORD=mina
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5440:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  data:
